package:
  name: ray
  version: "0.6.0"

build:
  number: 1

requirements:
  build:
    - python
    - pip
    - libgcc
    - colorama
    - redis-py
    - pytest
    - click
    - pyyaml
    - python-flatbuffers
    - funcsigs
    - atomicwrites
    - pluggy >=0.7 
    - more-itertools >=4.0.0
    - attrs >=17.4.0
    - py >=1.5.0
    - numpy >=1.8.2
    - six >=1.10.0
    - wheel >=0.26
  run:
    - python
    - numpy >=1.8.2
    - libgcc
    - colorama
    - redis-py
    - pytest
    - click
    - pyyaml
    - python-flatbuffers
    - funcsigs
    - atomicwrites  
    - pluggy >=0.7  
    - more-itertools >=4.0.0
    - attrs >=17.4.0
    - py >=1.5.0
    - six >=1.10.0

test:
  imports:
    - ray

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow
