package:
  name: ray
  version: 0.6.0
source:
  git_url: https://github.com/ray-project/ray.git

requirements:
  build:
    - numpy
  host:
    - setuptools
  run:
    - python

test:
  imports:
    - ray

about:
  home:
  license:
  license_file:

#   Downloading https://files.pythonhosted.org/packages/f5/00/5253aff5e747faf10d8ceb35fb5569b848cde2fdc13685d42fcf63118bbc/redis-3.0.1-py2.py3-none-any.whl (61kB)
